[package]
name = "rust-todo-app"
version = "0.1.0"
authors = ["Tatu Pesonen <pannariiz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

